// Generated by gencpp from file locobot_simulation/LogicalImage.msg
// DO NOT EDIT!


#ifndef LOCOBOT_SIMULATION_MESSAGE_LOGICALIMAGE_H
#define LOCOBOT_SIMULATION_MESSAGE_LOGICALIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <locobot_simulation/Model.h>
#include <geometry_msgs/Pose.h>

namespace locobot_simulation
{
template <class ContainerAllocator>
struct LogicalImage_
{
  typedef LogicalImage_<ContainerAllocator> Type;

  LogicalImage_()
    : header()
    , models()
    , pose()  {
    }
  LogicalImage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , models(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::locobot_simulation::Model_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::locobot_simulation::Model_<ContainerAllocator> >::other >  _models_type;
  _models_type models;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::locobot_simulation::LogicalImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::locobot_simulation::LogicalImage_<ContainerAllocator> const> ConstPtr;

}; // struct LogicalImage_

typedef ::locobot_simulation::LogicalImage_<std::allocator<void> > LogicalImage;

typedef boost::shared_ptr< ::locobot_simulation::LogicalImage > LogicalImagePtr;
typedef boost::shared_ptr< ::locobot_simulation::LogicalImage const> LogicalImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::locobot_simulation::LogicalImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::locobot_simulation::LogicalImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::locobot_simulation::LogicalImage_<ContainerAllocator1> & lhs, const ::locobot_simulation::LogicalImage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.models == rhs.models &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::locobot_simulation::LogicalImage_<ContainerAllocator1> & lhs, const ::locobot_simulation::LogicalImage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace locobot_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::locobot_simulation::LogicalImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::locobot_simulation::LogicalImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locobot_simulation::LogicalImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locobot_simulation::LogicalImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locobot_simulation::LogicalImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locobot_simulation::LogicalImage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::locobot_simulation::LogicalImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce67e5d7268d09846f46b13669044ed7";
  }

  static const char* value(const ::locobot_simulation::LogicalImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce67e5d7268d0984ULL;
  static const uint64_t static_value2 = 0x6f46b13669044ed7ULL;
};

template<class ContainerAllocator>
struct DataType< ::locobot_simulation::LogicalImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "locobot_simulation/LogicalImage";
  }

  static const char* value(const ::locobot_simulation::LogicalImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::locobot_simulation::LogicalImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Model[] models\n"
"geometry_msgs/Pose pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: locobot_simulation/Model\n"
"string type\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 size\n"
"geometry_msgs/Vector3 min\n"
"geometry_msgs/Vector3 max\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::locobot_simulation::LogicalImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::locobot_simulation::LogicalImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.models);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LogicalImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::locobot_simulation::LogicalImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::locobot_simulation::LogicalImage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "models[]" << std::endl;
    for (size_t i = 0; i < v.models.size(); ++i)
    {
      s << indent << "  models[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::locobot_simulation::Model_<ContainerAllocator> >::stream(s, indent + "    ", v.models[i]);
    }
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCOBOT_SIMULATION_MESSAGE_LOGICALIMAGE_H
